### ISSUE TITLE
Create tests for command-line interpreter

### ISSUE THREAD

**Issue by wfspotz** [wfspotz/nb2html#1]
Task list:

- [x] Set up minimal resources to run CLI
    - Temporary directory, executable script (`nb2html.py`), jupyter notebook (`SimpleCitation.ipynb`), BibTeX database file (`ref.bib`), CSL file (`Harvard.csl`)
- [x] Test that the command runs
    - `Popen([sys.executable, 'nb2html.py', ...])`
    - No exceptions, HTML file is generated
- [x] Test that it basically works
    - Check that the generated HTML is sane
- [x] Test that important CLI arguments works as expected
    - Avoid CSL files that extract content from web

FYI @mpacer

**Comment by mpacer** [comment]
Awesome!
